"""Removed timeRange table

Revision ID: 0230e6467795
Revises: 1a2cd2716bec
Create Date: 2024-05-19 10:38:19.156618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0230e6467795'
down_revision = '1a2cd2716bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_range', schema=None) as batch_op:
        batch_op.drop_index('ix_time_range_groupID')

    op.drop_table('time_range')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_range',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('groupID', sa.INTEGER(), nullable=False),
    sa.Column('day', sa.VARCHAR(length=10), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=True),
    sa.Column('stop_time', sa.TIME(), nullable=True),
    sa.ForeignKeyConstraint(['groupID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('time_range', schema=None) as batch_op:
        batch_op.create_index('ix_time_range_groupID', ['groupID'], unique=False)

    # ### end Alembic commands ###
