"""Change password field by one

Revision ID: 0a3db236069c
Revises: 58b86fed7986
Create Date: 2024-04-29 15:12:46.990283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3db236069c'
down_revision = '58b86fed7986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userPasswords', sa.String(length=254), nullable=False))
        batch_op.drop_column('userPassword')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userPassword', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('userPasswords')

    # ### end Alembic commands ###
