"""Removed messaging capability

Revision ID: 1a2cd2716bec
Revises: a3cf6bcf3b1e
Create Date: 2024-05-18 19:40:55.737755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2cd2716bec'
down_revision = 'a3cf6bcf3b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('messages')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groupMembership', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('groupMembership')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messages', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
