"""Allow for storage of messages

Revision ID: 226f861e2c82
Revises: 47d3f0f50638
Create Date: 2024-05-13 14:14:55.953466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226f861e2c82'
down_revision = '47d3f0f50638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messages', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('messages')

    # ### end Alembic commands ###
