"""Added relations

Revision ID: 22cd0a4050d4
Revises: 391c8ffe3a7c
Create Date: 2024-04-26 10:31:30.721166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cd0a4050d4'
down_revision = '391c8ffe3a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userID', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_groups_userID'), ['userID'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['userID'], ['userID'])

    with op.batch_alter_table('reply_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userID', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('requestID', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'groups', ['requestID'], ['groupID'])
        batch_op.create_foreign_key(None, 'users', ['userID'], ['userID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('requestID')
        batch_op.drop_column('userID')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_groups_userID'))
        batch_op.drop_column('userID')

    # ### end Alembic commands ###
