"""Initial table setup

Revision ID: 391c8ffe3a7c
Revises: 
Create Date: 2024-04-26 10:01:47.885909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391c8ffe3a7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('groupID', sa.Integer(), nullable=False),
    sa.Column('postCreationDate', sa.DateTime(), nullable=False),
    sa.Column('tagOne', sa.String(length=8), nullable=False),
    sa.Column('tagTwo', sa.String(length=8), nullable=True),
    sa.Column('tagThree', sa.String(length=8), nullable=True),
    sa.Column('studentAvailability', sa.String(length=255), nullable=False),
    sa.Column('requiredStudents', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('groupID')
    )
    op.create_table('reply_messages',
    sa.Column('messageID', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('messageCreationDate', sa.DateTime(), nullable=False),
    sa.Column('availability', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('messageID')
    )
    op.create_table('users',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('userEmail', sa.String(length=160), nullable=False),
    sa.Column('hashedPassword', sa.String(length=255), nullable=False),
    sa.Column('creationDate', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('userEmail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('reply_messages')
    op.drop_table('groups')
    # ### end Alembic commands ###
