"""Add group title

Revision ID: 3e22a6442a82
Revises: 06ecca5dc51e
Create Date: 2024-05-12 15:07:22.917950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e22a6442a82'
down_revision = '06ecca5dc51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groupName', sa.String(length=220), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('groupName')

    # ### end Alembic commands ###
