"""Added a few additional fields

Revision ID: 47d3f0f50638
Revises: 3e22a6442a82
Create Date: 2024-05-12 15:21:40.134189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d3f0f50638'
down_revision = '3e22a6442a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groupDescription', sa.String(length=252), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('groupDescription')

    # ### end Alembic commands ###
