"""added the week form

Revision ID: 5fe874698861
Revises: 1aabef31418c
Create Date: 2024-05-17 22:15:50.440426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe874698861'
down_revision = '1aabef31418c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.drop_column('studentAvailability')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('studentAvailability', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
