"""Added members field

Revision ID: a3cf6bcf3b1e
Revises: 
Create Date: 2024-05-18 15:47:45.232747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cf6bcf3b1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(length=150), nullable=False),
    sa.Column('userName', sa.Integer(), nullable=False),
    sa.Column('userEmail', sa.String(length=160), nullable=False),
    sa.Column('userPasswords', sa.String(length=254), nullable=True),
    sa.Column('creationDate', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('userEmail'),
    sa.UniqueConstraint('userName')
    )
    op.create_table('groups',
    sa.Column('groupID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('postCreationDate', sa.DateTime(), nullable=False),
    sa.Column('groupTitle', sa.String(length=255), nullable=False),
    sa.Column('tagOne', sa.String(length=8), nullable=False),
    sa.Column('tagTwo', sa.String(length=8), nullable=True),
    sa.Column('tagThree', sa.String(length=8), nullable=True),
    sa.Column('requiredStudents', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('members', sa.String(), nullable=False),
    sa.Column('messages', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('groupID')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_userID'), ['userID'], unique=False)

    op.create_table('time_range',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('groupID', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('stop_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['groupID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('time_range', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_range_groupID'), ['groupID'], unique=False)

    op.create_table('time_slot',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('groupID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['groupID'], ['groups.groupID'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_slot_groupID'), ['groupID'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_slot_userID'), ['userID'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_slot_userID'))
        batch_op.drop_index(batch_op.f('ix_time_slot_groupID'))

    op.drop_table('time_slot')
    with op.batch_alter_table('time_range', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_range_groupID'))

    op.drop_table('time_range')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_userID'))

    op.drop_table('groups')
    op.drop_table('users')
    # ### end Alembic commands ###
