"""users table

Revision ID: aac714af405a
Revises: 
Create Date: 2024-05-16 16:52:28.731186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac714af405a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(length=150), nullable=False),
    sa.Column('userName', sa.Integer(), nullable=False),
    sa.Column('userEmail', sa.String(length=160), nullable=False),
    sa.Column('userPasswords', sa.String(length=254), nullable=True),
    sa.Column('creationDate', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('userEmail'),
    sa.UniqueConstraint('userName')
    )
    op.create_table('groups',
    sa.Column('groupID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('postCreationDate', sa.DateTime(), nullable=False),
    sa.Column('groupTitle', sa.String(length=255), nullable=False),
    sa.Column('tagOne', sa.String(length=8), nullable=False),
    sa.Column('tagTwo', sa.String(length=8), nullable=True),
    sa.Column('tagThree', sa.String(length=8), nullable=True),
    sa.Column('studentAvailability', sa.String(length=255), nullable=False),
    sa.Column('requiredStudents', sa.Integer(), nullable=False),
    sa.Column('mondayStartTime', sa.String(length=16), nullable=False),
    sa.Column('mondayEndTime', sa.String(length=16), nullable=False),
    sa.Column('tuesdayStartTime', sa.String(length=16), nullable=False),
    sa.Column('tuesdayEndTime', sa.String(length=16), nullable=False),
    sa.Column('webnesdayStartTime', sa.String(length=16), nullable=False),
    sa.Column('webnesdayEndTime', sa.String(length=16), nullable=False),
    sa.Column('thursdayStartTime', sa.String(length=16), nullable=False),
    sa.Column('thursdayEndTime', sa.String(length=16), nullable=False),
    sa.Column('fridayStartTime', sa.String(length=16), nullable=False),
    sa.Column('fridayEndTime', sa.String(length=16), nullable=False),
    sa.Column('saterdayStartTime', sa.String(length=16), nullable=False),
    sa.Column('saterdayEndTime', sa.String(length=16), nullable=False),
    sa.Column('sundayStartTime', sa.String(length=16), nullable=False),
    sa.Column('sundayEndTime', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('groupID')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_userID'), ['userID'], unique=False)

    op.create_table('reply_messages',
    sa.Column('messageID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('requestID', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('messageCreationDate', sa.DateTime(), nullable=False),
    sa.Column('availability', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['requestID'], ['groups.groupID'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('messageID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply_messages')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_userID'))

    op.drop_table('groups')
    op.drop_table('users')
    # ### end Alembic commands ###
